#!/bin/bash
set -xeu
if [[ $# -eq 0 ]]; then
    echo "Usage: $0 [-bd] <specfile>"
    exit 0
fi
builddep=0
debug=0
while getopts "bd" opt;do
    case $opt in
        b )
            builddep=1
            ;;
        d )
            debug=1
            ;;
    esac
done
shift $((OPTIND-1))
cd @REPO_DIR@
spec=$1
[[ $builddep -eq 1 ]] && sudo /usr/bin/yum-builddep $spec

if [[ debug -eq 1 ]];then
    echo "Content of ~/..rpmmacros" > /dev/stderr
    cat ~/.rpmmacros >  /dev/stderr
fi
spectool -R -g $spec
rpmbuild -ba $spec
DistroDir=@REPO_DIR@/epel-@CENTOS_VERSION@
Nvr=$(rpm -q --qf '%{nvr}' --specfile $spec)
Arch=$(rpm -q --qf '%{arch}' --specfile $spec)
if [[ $Arch = "noarch" ]] ;then
    mv -f $DistroDir/noarch/* $DistroDir/x86_64
    rm -fr $DistroDir/noarch
    mkdir -p $DistroDir/i386
    cd $DistroDir/i386
    rm -f *.noarch.rpm
    ln -s ../x86_64/*.noarch.rpm .
    cd -
fi
cd $DistroDir
for archDir in SRPMS x86_64 i386 ;do 
    createrepo --update --database --verbose --delta $archDir
done 


