#!/bin/bash
### NAME
###     run - run the centos-repo-builder
###
### SYNOPSIS
###     run [Options] <specFilename> <repoDir>
###     run [Options] -S [rsync_src] <specFilename>
###
### DESCRIPTION
###     This program builds RPMs from a given SPEC file,
### update to provided version, then update yum repodata.
###
### This program can get the repositoy from local or remote directory.
###
### With local reposity
###
### <specfilename> is the RPM SPEC filename. Currently, the SPEC file
### need to be in repoDir.
### <distroVersion> is the CentOS version you like to build from.
### Like 7 to build from CentOS 7.
###
###
### <repoDir> is the directory that will host repository data and
### RPM files. <repoDir> is also a volume for docker.
###

set -eu
shopt -s globstar
ScriptDir=$(dirname $(realpath $0))
ProgramName=$(basename $0)
DOCKER_IMAGE=docker.io/zanata/centos-repo-builder

##=== function definition Start ===
## Get EXIT_STATUS and other environment variables from zanata-scripts
source <(curl -q https://raw.githubusercontent.com/zanata/zanata-scripts/master/zanata-env.sh)

zanata_help_raw(){
    local script="$1"
    [ -z "$script" ] && script=$0
    sed -r -n -e '/^### ?/ {s|^### ?||p}' $script
}
##=== function definition End ===

DockerRunOptArray=()
## Arguments for /home/builder/build
ArgumentArray=()
ContainerName=
RsyncRemote=

###
### Options
while getopts "hbdO:S:D:u:" opt;do
    case $opt in
###     -h: Show detail help.
        h )
            zanata_help_raw $0
            exit ${EXIT_OK}
            ;;

###
###     -A <rsync options>:
###         rsync options. Option 'R' is also required for rsync to and from container
        A )
            ArgumentArray+=( -A "${OPTARG}" )
            ;;
###     -b: Install build dependencies in docker
###         It runs sudo yum-builddep <specfile> to install build
###         dependencies in docker.
        b )
            ArgumentArray+=( -b )
            ;;
###     -d: Debug mode
###         It will list .rpmmacros and some other debug information.
        d )
            ArgumentArray+=( -d )
            ;;
###     -n <name>: Container name
###         Default: centos<distroVersion>-builder
        n )
            ContainerName=$OPTARG
            ;;
###     -o <options>: Options for docker-run
        o )
            DockerRunOptArray+=( ${OPTARG} )
            ;;
###
###     -R [<host>:]<dir>:
###         Host and directory of remote repo.
        R )
            RsyncRemote=${OPTARG}
            ArgumentArray+=( -R "${OPTARG}" )
            ;;
###
###     -r Remove the container after execution
        r )
            DockerRunOptArray+=( --rm )
            ;;
###
###     -s <dir>: Directory for RPM sourcedir
        s )
            DockerRunOptArray+=( -v $(realpath $OPTARG):/rpmbuild/SOURCES:Z )
            ;;
    esac
done
shift $((OPTIND-1))

if [[ $# -lt 2 ]]; then
    zanata_help_raw $0
    exit ${EXIT_FATAL_INVALID_OPTIONS}
fi

CentosVersion=$1
SpecFile=$2
shift 2

if [[ -z $RsyncRemote ]]; then
    if [[ -z ${1:-} ]]; then
        zanata_help_raw $0
        echo "Please provide either <RepoDir> or -R <[host:]dir>" > /dev/stderr
        exit ${EXIT_FATAL_INVALID_OPTIONS}
    fi
fi

RepoDir=$(realpath $1)

[[ -z ${ContainerName} ]] && ContainerName="centos${CentosVersion}-builder"

if [[ -n ${RsyncRemote} ]]; then
    VolumeName=zanata-el-${CentosVersion}-repo
    if ! docker volume  ls  -q | grep $VolumeName ;then
        docker volume create --name $VolumeName
    fi
    DockerRunOptArray+=( -v $VolumeName:/repo:Z )
else
    DockerRunOptArray+=( -v $RepoDir:/repo:Z )
fi

docker run ${DockerRunOptArray[@]:-} -it --name $ContainerName -v $RepoDir:/repo:Z docker.io/zanata/centos-repo-builder:$CentosVersion ${ArgumentArray[@]:-} $SpecFile $@

###
### EXIT_STATUS
###    See https://github.com/zanata/zanata-scripts/blob/master/zanata-env.sh
