version: "2.1"
services:
  zanatadb:
    image: "mariadb:10.1"
    container_name: "zanatadb"
    command: "--character-set-server=utf8 --collation-server=utf8_general_ci"
    volumes:
      - zanata-db:/var/lib/mysql:Z
    environment: 
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=${ZANATA_MYSQL_USER:-zanata}
      - MYSQL_PASSWORD=${ZANATA_MYSQL_PASSWORD:-password}
      - MYSQL_DATABASE=${ZANATA_MYSQL_DATABASE:-zanata}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
  zanata:
    image: "zanata/server:${ZANATA_VERSION:-latest}"
    container_name: zanata
    ports:
      - "${ZANATA_PORT:-8080}:8080"
    volumes:
      - zanata-files:/var/lib/zanata
    depends_on:
      zanatadb:
        condition: service_healthy
    environment:
      - ZANATA_HOME=/var/lib/zanata
      - DB_PORT_3306_TCP_ADDR=zanatadb
      - DB_ENV_MYSQL_USER=${ZANATA_MYSQL_USER:-zanata}
      - DB_ENV_MYSQL_PASSWORD=${ZANATA_MYSQL_PASSWORD:-password}
      - DB_ENV_MYSQL_DATABASE=${ZANATA_MYSQL_DATABASE:-zanata}
volumes:
  zanata-files:
  zanata-db:
